/* Cohorte sintética para las maquetas. Mismas formas que src/lib/types.ts del producto; ninguna
   persona es real y ningún dato viene de una ficha clínica. */
(function () {
  const franja = (marcas, hasta) =>
    Array.from({ length: 42 }, (_, i) => (i + 1 <= hasta ? marcas[i + 1] ?? null : null));

  const COHORTE = [
    {
      id: "camila",
      nombre: "Camila R.",
      codigo: "PM-042",
      edad: 31,
      tipoParto: "cesárea",
      dia: 9,
      nivel: "alto",
      region: "Metropolitana",
      establecimiento: "Hospital San José",
      fechaParto: "28 ago 2026",
      razonamiento:
        "Hallazgos compatibles con endometritis puerperal: fiebre referida, dolor uterino y loquios de mal olor al día 9. Sugiere evaluación presencial dentro del día.",
      cita: "§3.1",
      franja: franja({ 2: "bajo", 3: "bajo", 5: "bajo", 7: "medio", 8: "medio", 9: "alto" }, 9),
      alertas: [
        {
          id: "a1",
          nivel: "alto",
          at: "14 min",
          titulo: "Fiebre referida con loquios de mal olor al día 9",
          accion: "Sugiere evaluación presencial en el CESFAM dentro del día. Contactar antes del mediodía.",
          cita: "§3.1",
        },
      ],
      mensajes: [
        { de: "sistema", texto: "Hola Camila, vas en el día 9. ¿Cómo está la herida hoy?", hora: "09:12" },
        { de: "puerpera", texto: "me duele la guata y me huele feo", hora: "11:40" },
        { de: "sistema", texto: "¿Has tenido fiebre o escalofríos? Le voy a avisar a tu matrona.", hora: "11:40" },
        { de: "puerpera", texto: "si, anoche andaba afiebrada y con frío", hora: "11:43" },
      ],
      ficha: {
        "Semanas de gestación": "38",
        "Trabajo de parto": "6 h",
        Anestesia: "Sí · raquídea",
        "Enfermedades del embarazo": "Síndrome hipertensivo del embarazo",
        Paridad: "2 partos previos",
        Tabaco: "No",
        IMC: "29,4",
        "Contacto de emergencia": "Hermana · +56 9 XXXX XXXX",
      },
      factores: [
        "Antecedente de trastorno hipertensivo del embarazo: cualquier señal de §2 escala a alto sin esperar cifra de presión (§8, excepción única).",
        "Cesárea con IMC sobre 29: prioriza dentro de la categoría los hallazgos de herida operatoria.",
      ],
    },
    {
      id: "monica",
      nombre: "Mónica P.",
      codigo: "PM-118",
      edad: 27,
      tipoParto: "vaginal",
      dia: 11,
      nivel: "medio",
      region: "Biobío",
      establecimiento: "Hospital Las Higueras",
      fechaParto: "26 ago 2026",
      razonamiento:
        "Dolor mamario unilateral sin fiebre ni compromiso general. Sugiere control de técnica de lactancia y reevaluar en 24 horas.",
      cita: "§4.2",
      franja: franja({ 2: "bajo", 4: "bajo", 6: "bajo", 10: "medio", 11: "medio" }, 11),
      alertas: [
        {
          id: "a2",
          nivel: "medio",
          at: "2 h",
          titulo: "Dolor mamario unilateral desde el día 10",
          accion: "Revisar hoy: control de técnica de lactancia. Reevaluar si aparece fiebre.",
          cita: "§4.2",
        },
      ],
      mensajes: [
        { de: "sistema", texto: "Hola Mónica, día 11. ¿Cómo va la lactancia?", hora: "08:30" },
        { de: "puerpera", texto: "me duele harto un pecho, el izquierdo", hora: "10:02" },
      ],
      ficha: { "Semanas de gestación": "40", Episiotomía: "Sí", Paridad: "Primer parto", Tabaco: "No" },
      factores: ["Primer parto: la instalación de la lactancia concentra las consultas de la semana 2 (§4)."],
    },
    {
      id: "javiera",
      nombre: "Javiera S.",
      codigo: "PM-007",
      edad: 34,
      tipoParto: "cesárea",
      dia: 28,
      nivel: "bajo",
      region: "Valparaíso",
      establecimiento: "Hospital Carlos Van Buren",
      fechaParto: "09 ago 2026",
      razonamiento: "",
      cita: "",
      franja: franja({ 3: "bajo", 8: "bajo", 15: "bajo", 21: "bajo", 27: "bajo", 28: "bajo" }, 28),
      alertas: [],
      mensajes: [
        { de: "sistema", texto: "Día 28. ¿Cómo has estado esta semana?", hora: "09:00" },
        { de: "puerpera", texto: "bien, cansada nomás pero bien", hora: "09:22" },
      ],
      ficha: { "Semanas de gestación": "39", Anestesia: "Sí · raquídea", Paridad: "1 parto previo" },
      factores: [],
    },
    {
      id: "fernanda",
      nombre: "Fernanda A.",
      codigo: "PM-201",
      edad: 22,
      tipoParto: "vaginal",
      dia: 4,
      nivel: "medio",
      region: "Araucanía",
      establecimiento: "Hospital Hernán Henríquez",
      fechaParto: "02 sept 2026",
      razonamiento:
        "Sangrado que aumenta respecto de los días previos, sin cifras de presión ni compromiso hemodinámico referido. Sugiere control presencial hoy.",
      cita: "§2.3",
      franja: franja({ 1: "bajo", 2: "bajo", 4: "medio" }, 4),
      alertas: [
        {
          id: "a3",
          nivel: "medio",
          at: "35 min",
          titulo: "Aumento del sangrado al día 4",
          accion: "Revisar hoy. Consultar por número de apósitos y presencia de coágulos.",
          cita: "§2.3",
        },
      ],
      mensajes: [
        { de: "puerpera", texto: "me está bajando harto y me salió un coágulo grande", hora: "12:15" },
      ],
      ficha: { "Semanas de gestación": "37", Paridad: "Primer parto", Tabaco: "Ocasional" },
      factores: ["Primer parto y día 4: el tramo donde el protocolo concentra la hemorragia tardía (§2)."],
    },
    {
      id: "rocio",
      nombre: "Rocío M.",
      codigo: "PM-090",
      edad: 29,
      tipoParto: "cesárea",
      dia: 17,
      nivel: "bajo",
      region: "Metropolitana",
      establecimiento: "Hospital Sótero del Río",
      fechaParto: "20 ago 2026",
      razonamiento: "",
      cita: "",
      franja: franja({ 2: "bajo", 5: "bajo", 9: "bajo" }, 17),
      alertas: [],
      mensajes: [],
      ficha: {},
      factores: [],
      silencio: "8 d en silencio",
    },
    {
      id: "antonia",
      nombre: "Antonia M.",
      codigo: "PM-156",
      edad: 36,
      tipoParto: "vaginal",
      dia: 6,
      nivel: "bajo",
      region: "Maule",
      establecimiento: "Hospital de Talca",
      fechaParto: "31 ago 2026",
      razonamiento: "",
      cita: "",
      franja: franja({ 1: "bajo", 2: "bajo", 3: "bajo", 5: "bajo", 6: "bajo" }, 6),
      alertas: [],
      mensajes: [{ de: "puerpera", texto: "estamos bien las dos, cansada nomás", hora: "10:10" }],
      ficha: { "Semanas de gestación": "40", Paridad: "3 partos previos" },
      factores: [],
    },
    {
      id: "valentina",
      nombre: "Valentina C.",
      codigo: "PM-033",
      edad: 25,
      tipoParto: "cesárea",
      dia: 34,
      nivel: "bajo",
      region: "Coquimbo",
      establecimiento: "Hospital de Ovalle",
      fechaParto: "03 ago 2026",
      razonamiento: "",
      cita: "",
      franja: franja({ 4: "bajo", 12: "bajo", 20: "bajo", 30: "bajo" }, 34),
      alertas: [],
      mensajes: [],
      ficha: {},
      factores: [],
      silencio: "4 d en silencio",
    },
  ];

  const SUGERENCIAS = [
    "estamos bien las dos, cansada nomás",
    "me está bajando harto y me salió un coágulo grande",
    "ando afiebrada y me huele feo abajo",
  ];

  window.MATRIA = { COHORTE, SUGERENCIAS, ORDEN: { alto: 0, medio: 1, bajo: 2 } };
})();
